# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPaZurY0xeQW9slcYZBQkOGXNPGABOMs
"""

a=10
b=3
print("addition:",a+b)
print("subtraction:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("modulus division:",a%b)
print("floor division:",a//b)
print("exponent:",a**b)

x=5
y=8
print("x==y:",x==y)
print("x!=y:",x!=y)
print("x>y:",x>y)
print("x<y:",x<y)
print("x>=y:",x>=y)
print("x<=y:",x<=y)

x=5
y=8
print("x==y:",x==y)
print("x!=y:",x!=y)
print("x>y:",x>y)
print("x<y:",x<y)
print("x>=y:",x>=y)
print("x<=y:",x<=y)

x=5
y=8
print("x==y:",x==y)
print("x!=y:",x!=y)
print("x>y:",x>y)
print("x<y:",x<y)
print("x>=y:",x>=y)
print("x<=y:",x<=y)

x=5
y=8
print("x==y:",x==y)
print("x!=y:",x!=y)
print("x>y:",x>y)
print("x<y:",x<y)
print("x>=y:",x>=y)
print("x<=y:",x<=y)

a=10
b=5
print(a+b)
print(a-b)
print(a*b)
print(a/b)

a=int(input("enter the number: "))
for i in range(1,11):
  print(f"{a}*{i}={a*i}")

name="aswan"
age=18
course="eletrical"
print(f"\n student info:\nname:{name}\nage:{age}\ncourse:{course}")

a=int(input("enter the number:"))
b=int(input("enter the number:"))
print(f"a+=5:{a+=5}")
print(f"a-=5:{a-=3}")
print(f"a*=5:{a*=5}")
print(f"a/=5:{a/=5}")
print(f"a%=5:{a%=5}")

# Method 1: Using a temporary variable
x = 10
y = 5
print(f"Before swapping (using temp variable): x = {x}, y = {y}")

temp = x
x = y
y = temp
print(f"After swapping (using temp variable): x = {x}, y = {y}")

# Method 2: Using tuple packing and unpacking (Pythonic way)
a = 20
b = 15
print(f"\nBefore swapping (using tuple): a = {a}, b = {b}")

a, b = b, a
print(f"After swapping (using tuple): a = {a}, b = {b}")

name="aswan"
age=17
course="mechanical"
print(f"\n student info:\nname:{name}\nage:{age}\n
course:{corse}")

a=int(input("enter the number:"))
b=int(input("enter the number:"))
print(f"a&b:{a&b}")
print(f"a|b:{a|b}")
print(f"a^b:{a^b}")
print(f"a~b:{a~b}")
print(f"a<<b:{a<<b}")
print(f"a>>b:{a>>b}")

fruits=["apple","banana","cherry"]
print("banana in fruits:","banana" in fruits)
print("mango not in fruits:","mango" not in fruits)
print("mango in fruits:","mango" in fruits)

a=int(input("enter a number"))
b=int(input("enter b number"))
print("a and b:",a and b)
print("a or b:",a or b)
print(" not b:",not b)
print("not a:",not a)

weight=float(input("enter weight(kg)"))
height=float(input("enter height(cm)"))
bmi=weight/(height**2)
print("bmi:",bmi)
if bmi<18.5:
  print("under weight")
elif bmi<24.9:
  print("normal weight")
elif bmi<29.9:
  print("over weight")
else:
  print("obsuse")

def factorial(n):
  """Calculates the factorial of a non-negative integer using recursion."""
  if n == 0:
    return 1
  else:
    return n * factorial(n-1)

# Example usage:
num = 5
print(f"The factorial of {num} is {factorial(num)}")

import numpy as np


array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print("Array 1:\n", array1)
print("Array 2:\n", array2)
element_wise_multiplication = array1 * array2
print("\nElement-wise multiplication:\n", element_wise_multiplication)

matrix_multiplication = array1 @ array2  # or np.dot(array1, array2)
print("\nMatrix multiplication:\n", matrix_multiplication)